import '../styles/globals.css';
import type { AppProps } from 'next/app';
import { Roboto } from '@next/font/google';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import createMagic from '@utils/magic-login';
import Loading from '@components/loading/Loading';

const roboto = Roboto({
	weight: ['400', '500', '700'],
	style: ['italic', 'normal'],
	subsets: ['latin'],
});
export default function App({ Component, pageProps }: AppProps) {
	const router = useRouter();
	const [isLoading, setIsLoading] = useState(false);
	// useEffect(() => {
	// 	setIsLoading(true);
	// 	(async () => {
	// 		const isLoggedIn = await createMagic().user.isLoggedIn();
	// 		if (isLoggedIn) {
	// 			router.push('/');
	// 		} else {
	// 			router.push('/login');
	// 		}
	// 	})();
	// }, []);
	useEffect(() => {
		const handleRouteChange = () => {
			setIsLoading(false);
		};
		router.events.on('routeChangeComplete', handleRouteChange);
		router.events.on('routeChangeError', handleRouteChange);
		return () => {
			router.events.off('routeChangeComplete', handleRouteChange);
			router.events.off('routeChangeError', handleRouteChange);
		};
	}, [router]);
	return (
		<>
			<Head>
				<meta name="viewport" content="initial-scale=1.0, width=device-width" />
				<meta name="description" content="The netflix - movie website generated by s1mpleOW" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{isLoading ? (
				<div className="flex items-center justify-center mt-20">
					<Loading></Loading>
				</div>
			) : (
				<main className={roboto.className}>
					<Component {...pageProps} />
				</main>
			)}
		</>
	);
}
